# Generated by Django 4.1.7 on 2023-08-04 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=5000)),
                ('date', models.DateField()),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.adventure')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=5000)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.adventure')),
                ('day', models.ManyToManyField(related_name='locations', to='adventure.day')),
            ],
        ),
    ]
