# Generated by Django 4.2.4 on 2023-08-17 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_adventure_author_adventure_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='day',
        ),
        migrations.AddField(
            model_name='location',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adventure.day'),
            preserve_default=False,
        ),
    ]
